# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4cb11113de17f7b1f56ff65a663b8e88b03cd1b064c905b4ff16accb1d4a132270c4085da0db3947149a727ea165c906c51f691cf06e91bd25866bfcf67edcf

test:
  secret_key_base: ff82e740bdf415135da3b0170aaf97e0dde0a8df16888d22f2a4921f971236bbf8abb616430e3933a03b90436f05a4ed0f195db74d05293b824bfb4e293ec4a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
